name: angular-build-and-deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: angular-build-and-deploy-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  id-token: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Run Tests
        run: npm test -- --no-watch --no-progress --browsers=ChromeHeadless

      - name: Build Angular App
        run: npm run build -- --configuration production

      - name: Upload Production Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: angular-dist
          path: dist

  docker-build-and-push:
    needs: build-and-test
    runs-on: ubuntu-latest
    timeout-minutes: 20
    if: github.event_name != 'pull_request'
    environment:
      name: production
    permissions:
      contents: read
      id-token: write
      packages: write
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: angular-dist
          path: dist

      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker Image
        run: docker build -t ghcr.io/${{ github.repository_owner }}/angular-demo-docker:${{ github.sha }} .

      - name: Push Docker Image
        run: docker push ghcr.io/${{ github.repository_owner }}/angular-demo-docker:${{ github.sha }}

  codeql-analysis:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript

      - name: Autobuild
        uses: github/codeql-action/autobuild@v3

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
